[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20"
  NPM_USE_PRODUCTION = "false"
  # Increase timeout for large builds
  NODE_OPTIONS = "--max-old-space-size=4096"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers for better caching and performance of large files
[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Encoding = "gzip"

# Specific headers for the ICD-10 database
[[headers]]
  for = "/data/icd10-database-compact.json"
  [headers.values]
    Cache-Control = "public, max-age=86400" # 24 hours
    Content-Type = "application/json"